server:
  port: 9090
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true 
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:mysql://localhost:3306/account?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  cloud:
    stream:
      bindings:
        register.customer:
          contentType: application/json
          destination: register-customer
          binder: local_rabbit
        register.customer:
          contentType: application/json
          destination: ${spring.cloud.stream.bindings.register.customer.destination}
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
