server:
  port: 9092
spring:
  cloud:
    stream:
      bindings:
        register.customer:
          contentType: application/json
          destination: register-customer
          binder: local_rabbit
          group: register.documents
        decline-customer:
          contentType: application/json
          destination: decline-customer
          binder: local_rabbit 
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
