server:
  port: 9091
spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: fake
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
    url: jdbc:mysql://localhost:3306/account?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  cloud:
    stream:
      bindings:
        notify-stage:
          contentType: application/json
          destination: notify-stage
          binder: local_rabbit
          group: register.mail
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /

test.email.remetente: teste@naoresponser.com
